version: '3.3'
services:
  deleter:
    build:
      context: ..
      dockerfile: Dockerfile
    ports:
      - 8000:80
    env_file: .env
    volumes:
      - ../storage/app/requests:/var/www/app/storage/app/requests
